export enum CreditCardTypes {
  DEFAULT = '0',
  VISA = '1',
  MASTERCARD = '2',
  MAESTRO = '3',
  AMERICAN_EXPRESS = '4',
  DINERS_CLUBS = '5',
  DISCOVER = '6',
  JCB = '9',
  DANKORT = '11',
  HIPERCARD = '12',
  ELO = '13',
  AURA = '14',
  NARANJA = '15',
  MIR = '16',
  CHINA_UNION_PAY = '17',
  POSTEPAY = '18',
}
