export enum NextActionType {
  checkStatus = 'check_status',
  showFields = 'show_fields',
  statusUpdated = 'status_updated',
  showErrors = 'show_errors',
  showInitForm = 'show_init_form',
  redirect = 'redirect',
  threeDS = '3DS',
  specialButton = 'special_button',
  showQrCode = 'show_qr_code',
  showMobilePaymentScreen = 'show_mobile_payment_screen',
  hideForm = 'hide_form',
  showCashPaymentInstruction = 'show_cash_payment_instruction',
  serverError = 'server_error',
}
