export const enum EventName {
  error = 'error',
  initPayment = 'initPayment',
  initForm = 'initForm',
  submitForm = 'submitForm',
  getPaymentMethodsList = 'getPaymentMethodsList',
  getPaymentQuickMethods = 'getPaymentQuickMethods',
  getSavedMethods = 'getSavedMethods',
  getUserBalance = 'getUserBalance',
  getLegalComponentConfig = 'getLegalComponentConfig',
  getPaymentStatus = 'getPaymentStatus',
  legalComponentPing = 'legalComponentPing',
  legalComponentPong = 'legalComponentPong',
  financeDetails = 'financeDetails',
  nextAction = 'nextAction',
  warning = 'warning',
}
