export enum WebComponentTagName {
  TextComponent = 'psdk-text',
  SubmitButtonComponent = 'psdk-submit-button',
  PaymentMethodsComponent = 'psdk-payment-methods',
  SavedMethodsComponent = 'psdk-saved-methods',
  PriceTextComponent = 'psdk-price-text',
  FinanceDetailsComponent = 'psdk-finance-details',
  LegalComponent = 'psdk-legal',
  PaymentFormComponent = 'psdk-payment-form',
  StatusComponent = 'psdk-status',
  PhoneComponent = 'psdk-phone',
  CardNumberComponent = 'psdk-card-number',
  ThreeDsComponent = 'psdk-3ds',
  SelectComponent = 'psdk-select',
  CheckboxComponent = 'psdk-checkbox',
  UserBalanceComponent = 'psdk-user-balance',
}
